version: "3"

services:
  nginxproxy:
    depends_on:
      - client
      - game-server
      - socket-server
    image: nginx:alpine
    ports:
      - "80:80"
      # - "80:443"
      # - "443:3000"
    restart: always
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./https:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: client
    ports:
      - "5173:5173"
    volumes:
      - ./https:/usr/share/nginx/html

  game-server:
    build:
      context: ./game-server
      dockerfile: Dockerfile
    restart: always
    container_name: game-server
    ports:
      - "8080:8080"
    volumes:
      - ./https:/usr/share/nginx/html
      - ./game-server:/app/

  socket-server:
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    restart: always
    container_name: socket-server
    ports:
      - "5002:5002"
    volumes:
      - ./https:/usr/share/nginx/html
      - ./socket-server:/app/

  

  # cerbot:
  #   depends_on:
  #     - nginxproxy
  #   image: certbot/certbot
  #   container_name: cerbot
  #   volumes:
  #     - ./certbot:/etc/letsencrypt
  #     - ./https:/usr/share/nginx/html
  #   command: --dry-run certonly --webroot --webroot-path=/usr/share/nginx/html --email siaksiakx@gmail.com --agree-tos --no-eff-email -d highlighters.site -d www.highlighters.site --force-renewal
